apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shipping-deploy-task
spec:
  params:
  - name: namespace
    description: namespace
  workspaces:
  - name: source
# Fainal proejct
  steps:
    - name: kubectl
      image: "bitnami/kubectl"
      command: ["kubectl"]
      args: ["apply", "-f", "source/tekton-build/deploy/shipping-deploy.yaml","-n", "$(params.namespace)"]
