apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: project-admin
subjects:
  - kind: ServiceAccount
    name: fatimah-sac
    namespace: test
roleRef:
  kind: ClusterRole
  name: project-role
  apiGroup: rbac.authorization.k8s.io
